INSERT INTO oauth_client_details(
client_id,
resource_ids,
client_secret,
scope,
authorized_grant_types,
web_server_redirect_uri,
authorities,
access_token_validity,
refresh_token_validity,
additional_information,
autoapprove
)
VALUES (
'mobile_app',
'resource-server-rest-api',
'$2a$10$lO6BMcS1U6meax/oBPUgiui/zDrrbKr04G2uasgXMgcmm526rPShG',
'read,write',
'password,refresh_token',
NULL,
'MOBILE',
'3600',
'3800',
NULL,
NULL
);

INSERT INTO oauth_client_details (
client_id,
resource_ids,
client_secret,
scope,
authorized_grant_types,
web_server_redirect_uri,
authorities,
access_token_validity,
refresh_token_validity,
additional_information,
autoapprove
)
VALUES
(
'web',
'resource-server-rest-api',
'$2a$10$lO6BMcS1U6meax/oBPUgiui/zDrrbKr04G2uasgXMgcmm526rPShG',
'read,write',
'password,refresh_token',
NULL,
'WEB',
'3600',
'3800',
NULL,
NULL
);

INSERT INTO oauth_client_details (
client_id,
resource_ids,
client_secret,
scope,
authorized_grant_types,
web_server_redirect_uri,
authorities,
access_token_validity,
refresh_token_validity,
additional_information,
autoapprove
)
VALUES
(
'system',
'resource-server-rest-api',
'$2a$10$lO6BMcS1U6meax/oBPUgiui/zDrrbKr04G2uasgXMgcmm526rPShG',
'read,write',
'password,refresh_token',
NULL,
'SYSTEM',
'3600',
'3800',
NULL,
NULL
);