apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: authorization
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
      - name: authorization
        image: authorization:0.0.1.SNAPSHOT
        ports:
        - containerPort: 8080
